// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyVVXjrgY8bkjyIOCWtvJyNASEh4wWFQc',
    appId: '1:938615986190:web:1043150521cba9172ac45f',
    messagingSenderId: '938615986190',
    projectId: 'seeker-215cc',
    authDomain: 'seeker-215cc.firebaseapp.com',
    storageBucket: 'seeker-215cc.appspot.com',
    measurementId: 'G-DSEDDHNT79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClfJcpOSXJMzsOiyXZuSkajtUrhNhpZ7M',
    appId: '1:938615986190:android:64ddd2b565643bbd2ac45f',
    messagingSenderId: '938615986190',
    projectId: 'seeker-215cc',
    storageBucket: 'seeker-215cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK_n87N6Lp8IdCRh7paJFcBHwSWWPjjgA',
    appId: '1:938615986190:ios:2f50c5ec2b3f24322ac45f',
    messagingSenderId: '938615986190',
    projectId: 'seeker-215cc',
    storageBucket: 'seeker-215cc.appspot.com',
    iosBundleId: 'com.example.seeker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK_n87N6Lp8IdCRh7paJFcBHwSWWPjjgA',
    appId: '1:938615986190:ios:22eff15d71ff2d9a2ac45f',
    messagingSenderId: '938615986190',
    projectId: 'seeker-215cc',
    storageBucket: 'seeker-215cc.appspot.com',
    iosBundleId: 'com.example.seeker.RunnerTests',
  );
}
